moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.9.0
project:
  name: muka
  mode: personal
  description: ''
  created_at: '2026-01-26 22:15:11'
  template_version: 1.9.0
  optimized: false
